export const LOCAL_MEDIA_PRESET_VERSION = 1;

export const LOCAL_MEDIA = Object.freeze({
  heroPhoto: "/media/photos/pincipal%20principal.jpeg",
  galleryPhotos: Object.freeze([
    "/media/photos/uno.jpeg",
    "/media/photos/dos.jpeg",
    "/media/photos/tres.jpeg",
    "/media/photos/cuatro.jpeg",
    "/media/photos/cinco.jpeg",
    "/media/photos/seis.jpeg",
    "/media/photos/siete.jpeg",
    "/media/photos/ocho.jpeg",
    //"/media/photos/nueve.jpeg",
    //"/media/photos/dies.jpeg",
    //"/media/photos/once.jpeg",
    //"/media/photos/doce.jpeg",
    //"/media/photos/trece.jpeg",
    //"/media/photos/catorce.jpeg",
    //"/media/photos/quince.jpeg",
    //"/media/photos/diesiseis.jpeg",
    //"/media/photos/diesisiete.jpeg",
    //"/media/photos/diesiocho.jpeg",
    //"/media/photos/diesinueve.jpeg",
    //"/media/photos/viente.jpeg",
    //"/media/photos/veintiuno.jpeg",
    //"/media/photos/ventidos.jpeg",
  ]),
  audio: "/media/audio/photograph.mp3",
});
